CREATE TABLE tetyana_p15.employees_history (
  history_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id      NUMBER,
  first_name       VARCHAR2(100),
  last_name        VARCHAR2(100),
  email            VARCHAR2(100),
  phone_number     VARCHAR2(50),
  hire_date        DATE,
  job_id           VARCHAR2(10),
  salary           NUMBER,
  commission_pct   NUMBER,
  manager_id       NUMBER,
  department_id    NUMBER,
  fired_at         DATE
);
